import './globals.css'
import type { MetadataRoute } from 'next'
import { CompanyIntroduction, ServiceList, ContactInfo } from '@/components/home'
import { useAtomValue } from 'jotai'
import { companiesAtom } from '@/lib/state/atoms'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const companies = useAtomValue(companiesAtom);
  const company = companies[0] || { id: '', companyName: '', companyDescription: '', companyImage: '', services: [], contact: { name: '', email: '', message: '' } };

  return (
    <html lang="en">
      <body className={'bg-white dark:bg-[#111827]'}>
        <div className={'flex h-screen'}> 
          {children}
        </div>
      </body>
    </html>
  )
}

export const metadata: MetadataRoute = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
